# Generated by Django 3.0.2 on 2020-01-21 19:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('title', models.CharField(max_length=128)),
                ('date', models.DateField(default=datetime.date(2020, 1, 21))),
                ('cleared', models.BooleanField(default=False)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('paid_for', models.ManyToManyField(related_name='treats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
